---
title: "R Notebook"
output: html_notebook
---
 

```{r}
# import libraries
library("readr")
library("dplyr")

# load csv-file with all data
data <- read_csv("../0_DataPreparation/data.csv")

# sort data by Datum
data_sorted <- data %>% arrange(Datum)
head(data_sorted)

# delete unnecessary rows without Umsatz-data, which starts at 2013-07-01
data_sorted_filter <- data_sorted %>%
  filter(Datum >= as.Date('2013-07-01'))

# divide data into training and validation set
training_data <- data_sorted_filter %>% filter(Datum <= "2017-07-31")
validation_data <- data_sorted_filter %>% filter(Datum >= "2017-08-01" & Datum <= "2018-07-31")
test_data2 <- data_sorted_filter %>% filter(Datum >= "2018-08-01")

# check new data sets
head(training_data)
head(validation_data)
```


```{r}
#creating temperature bins labeled as 'Low', 'Medium', and 'High' 
# show distribution of data
hist(training_data$Temperatur)
# Define bin edges
bin_edges <- c(-Inf, 10, 20, Inf)

# Create bin labels
bin_labels <- c('Low', 'Medium', 'High')


# Use cut to assign values to bins
training_data$Temperature_Bin <- cut(training_data$Temperatur, breaks = bin_edges, labels = bin_labels, include.lowest = TRUE)

# Print the updated dataframe
print(training_data)
# model 1
mod_N <- lm(Umsatz ~ as.factor(Warengruppe) + as.factor(Temperature_Bin)+ as.factor(Wochenende), training_data)
summary(mod_N)
```

```{r}
#creating another variable named season 
#
library(dplyr)
install.packages("lubridate")
library(lubridate)

training_data <- training_data %>%
  mutate(season = ifelse(month(Datum) %in% c(3, 4, 5), "Spring",
                         ifelse(month(Datum) %in% c(6, 7, 8), "Summer",
                                ifelse(month(Datum) %in% c(9, 10, 11), "Fall", "Winter"))))

# Print the updated dataframe
print(training_data)
mod_N <- lm(Umsatz ~ as.factor(Warengruppe) + as.factor(Temperature_Bin)+ as.factor(Wochenende)+season+ KielerWoche + Schulferien, training_data)
summary(mod_N)
#Adjusted R-squared:  0.7359 
```

